### PR TITLE
start date of task inserted, day=0 for deadline is possible

### PR DESCRIPTION
**Pull request by iamamirhossein**
for deadline, day can be 0 if just one of year or month or week is not 0.
now we store start date for every task.

### CODE REVIEW

**Comment by shabane** [comment]
thanks again.
i changed a lot of thing about deadline. and your code helped me a lot.
you can see the log, i document it there.

for deadline, just like start time i set a date for it.
for example we have:
      "begintime":
           {
                   'y' : 20201,
                   'm': 5,
                   'd' : 21
           },
      "deadline" :  
           {
                    "y": 2021,
                    "m": 6,
                    "d": 7
           }

in the program just as simply as it was, you just say: 1 day, 2 week, 0 month, 0 year.
this numbers will convert to a valid date and than it will write in .to file.
now we should use your check_X as a function. because we need to implement it in EditTask().

again thank you for your contribute, i love your code,
i don't know how much free time do you have, and i don't want to bother or annoying you.
thanks a lot. in .to file there is a lot of task that i hould do it. who done theme i will appreciate him. specialy you.

**Comment by shabane** [comment]
> thanks again.
> i changed a lot of thing about deadline. and your code helped me a lot.
> you can see the log, i document it there.
> 
> for deadline, just like start time i set a date for it.
> for example we have:
> "begintime":
> {
> 'y' : 20201,
> 'm': 5,
> 'd' : 21
> },
> "deadline" :
> {
> "y": 2021,
> "m": 6,
> "d": 7
> }
> 
> in the program just as simply as it was, you just say: 1 day, 2 week, 0 month, 0 year.
> this numbers will convert to a valid date and than it will write in .to file.
> now we should use your check_X as a function. because we need to implement it in EditTask().
> 
> again thank you for your contribute, i love your code,
> i don't know how much free time do you have, and i don't want to bother or annoying you.
> thanks a lot. in .to file there is a lot of task that i hould do it. who done theme i will appreciate him. specialy you.

**Comment by iamamirhossein** [comment]
Thank you very very much, this program is going very well, and I try to help complete it whenever I have free time.
Good luck

**Comment by shabane** [comment]
> Thank you very very much, this program is going very well, and I try to help complete it whenever I have free time.
> Good luck

thank you very much. you helped a lot.

**Comment by shabane** [comment]
> Thank you very very much, this program is going very well, and I try to help complete it whenever I have free time.
> Good luck

hi again (:
now we reach at a good version.
if you can test the program.
the last thing that we should add is a trash to remove a list or a task,
and then we want to create a deb file and make it easy to install, if we could, we want to add this program to the repo of debian 
then to install it users just should type ```apt install to```
in this version we have two command-line:
1- intractive commnand-line
2- non-intractive command-line

if you can we will thanks full if you add the trash to the program.

trash is another dictionary key in .to file which store tasks/list which user removed it.

there is another key that store latest task doned.
this kay is used for git commit message.
you can type: ```to commit``` this will commit every thing that is in the latest key in .to file

**Comment by iamamirhossein** [comment]
Hi my friend. I'll be happy to code on this project again. But I will not be able to until i am sick. (covid19)

**Pull request closed without merging**
