### PR TITLE
change deadline from date to ymwd sample: 1y 2m 3w 1d

### PR DESCRIPTION
**Pull request by iamamirhossein**
user can set deadline like this: 1y, 2m, 0w, 2d
0< year <5
0< month <12 (for example 14 is 1 year and 2 months)
0< week < 4 (for example 9 is 2 months and 1 week)
1< day < 7 (for example 9 is 1 week and 2 days, cant be zero)

### CODE REVIEW

**Comment by shabane** [comment]
thank you very much, you are the best. too many thank's.
i will merge immediately; 

i change .to file. in .to file we have  a list that is for test the program, it's key is 'test'. just if you want to test something, use that tag. but again and again and again i will appreciate what you done.

after i should change something, like:

1- we should get a 0 day/none-day. 
because if you have one week to do something, you should can set week to 1. but now we forced to select one day and one week.

2- in line's that you get a deadline you typecast two time, but if you typecast exact after the input, cpu will be more free.

but you are the best, i love your work. again thank you.
print(10000000000000000 * 'thank you')

**Comment by shabane** [comment]
> thank you very much, you are the best. too many thank's.
> i will merge immediately;
> 
> i change .to file. in .to file we have a list that is for test the program, it's key is 'test'. just if you want to test something, use that tag. but again and again and again i will appreciate what you done.
> 
> after i should change something, like:
> 
> 1- we should get a 0 day/none-day.
> because if you have one week to do something, you should can set week to 1. but now we forced to select one day and one week.
> 
> 2- in line's that you get a deadline you typecast two time, but if you typecast exact after the input, cpu will be more free.
> 
> but you are the best, i love your work. again thank you.
> print(10000000000000000 * 'thank you')

other thing that we should add is a start time. 
this start time will indicate that when we start what task. 
and when we print the task's this value will help us to calculate how much time we have to done a task.

**Comment by iamamirhossein** [comment]
thank you SOOOO much bro.
yes i forgot insert "start time".
I will definitely work on the rest of the details.

**Comment by shabane** [comment]
> thank you SOOOO much bro.
> yes i forgot insert "start time".
> I will definitely work on the rest of the details.

no thank you! you did all that.
get some rest, now I'm working on start time and print the expire date.

**Comment by shabane** [comment]
> thank you SOOOO much bro.
> yes i forgot insert "start time".
> I will definitely work on the rest of the details.

now check it, i add it.

**Pull request merged**
