### PR TITLE
added deadline to task, like: 2021-05-17

### PR DESCRIPTION
**Pull request by iamamirhossein**
deadline just for insert task added, like this:
            {
                "done": "False",
                "task": "my task",
                "priority": 2,
                "deadline": "2021-05-18"
            }

### CODE REVIEW

**Comment by shabane** [comment]
> deadline just for insert task added, like this:
> {
> "done": "False",
> "task": "my task",
> "priority": 2,
> "deadline": "2021-05-18"
> }

thank you for your commit. i will merge it. in deadline do we need more specific date ? like time, hour and minute ?

**Comment by iamamirhossein** [comment]
thank you. There is usually no need to say the exact time, but if you want it i can add this option.

**Comment by shabane** [comment]
> thank you. There is usually no need to say the exact time, but if you want it i can add this option.

too many thank. can you add something that let user to indicate time more frindly.
like that he say tomorrow.
and/or he say a number with a letter like 2w, w is week and 2 show that is two week, or 4w.
d = day
w = week
m = month
 y = year
and we need some thing that let user select no date or infinit time.

**Comment by iamamirhossein** [comment]
Thank you very much, well I'm working on this.

**Pull request merged**
